/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClaseConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Patrick A
 */
public class frmIcioSesion extends javax.swing.JFrame {

    /**
     * Creates new form frmIcioSesion
     */
    ClaseConexionBD conexion = new ClaseConexionBD();
    Connection conect = conexion.conectarRegistro();
    public frmIcioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInicioSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        pswSesion = new javax.swing.JPasswordField();
        btnAceptarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio Sesion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioSesion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(204, 0, 51));
        lblInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicioSesion.setText("INICIO DE SESIÓN");
        jPanel1.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 50));

        lblUsuario.setBackground(new java.awt.Color(102, 102, 102));
        lblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("USUARIO:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, 40));

        lblContrasenia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(102, 102, 102));
        lblContrasenia.setText("CONTRASEÑA:");
        jPanel1.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 30));

        pswSesion.setBackground(new java.awt.Color(255, 255, 255));
        pswSesion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(pswSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 190, 40));

        btnAceptarSesion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAceptarSesion.setForeground(new java.awt.Color(51, 204, 0));
        btnAceptarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Botiquin.png"))); // NOI18N
        btnAceptarSesion.setText("INGRESAR");
        btnAceptarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3027579_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 190, 150));

        lblInformacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 243, 22));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarSesionActionPerformed
        // Evento al dar en "Aceptar
        String Usuario=txtUsuario.getText().trim();
        String  Contra=String.valueOf(pswSesion.getPassword());
        try {
            PreparedStatement pst = conect.prepareStatement(
                    "select * from registro where Usuario = ? and Contraseña =?" );
            pst.setString(1, Usuario);
            pst.setString(2, Contra);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                FrmPrincipal principal = new FrmPrincipal();
                principal.setVisible(true);
                principal.setBounds(0, 0, principal.getWidth(), principal.getHeight());
                principal.setLocationRelativeTo(null);
                this.setVisible(false);
            } // Cierre del if
            else{
                lblInformacion.setText("Usuario y contraseña inválidos");
            }
        } catch (Exception e) {
            lblInformacion.setText(e.toString());
        } // Cierre del Catch
    }//GEN-LAST:event_btnAceptarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIcioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIcioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIcioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIcioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIcioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pswSesion;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
