
package Formularios;

import Clases.ClaseConexionBD;
import Clases.ClaseLlenado;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public final class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creacion del formulario principal para el registro de los participantes
     * con el uso de base de datos mysql
     */
    ClaseConexionBD conexion = new ClaseConexionBD();
    Connection conect = conexion.conectar();

    public FrmPrincipal() {
        initComponents();
        mostrar();
        jtbBD.setEnabled(false);
        for (int i = 1; i <= 31; i++) {
            if (i < 10) {
                cbxDiaPD.addItem("0" + String.valueOf(i));
                cbxDiaSD.addItem("0" + String.valueOf(i));
                cbxDiaTD.addItem("0" + String.valueOf(i));
                cbxMesPD.addItem("0" + String.valueOf(i));
                cbxMesSD.addItem("0" + String.valueOf(i));
                cbxMesTD.addItem("0" + String.valueOf(i));
            } else {
                if (i <= 12) {
                    cbxMesPD.addItem(String.valueOf(i));
                    cbxMesSD.addItem(String.valueOf(i));
                    cbxMesTD.addItem(String.valueOf(i));
                }
                cbxDiaPD.addItem(String.valueOf(i));
                cbxDiaSD.addItem(String.valueOf(i));
                cbxDiaTD.addItem(String.valueOf(i));
            }
        }
    }
    // Crear una lista de arreglo para llenar la tabla
    ArrayList<ClaseLlenado> lista = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        panelTituloInicio = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        panelBusquedaInicio = new javax.swing.JPanel();
        lblBusquedaInicio = new javax.swing.JLabel();
        btnBuscarBusqueda = new javax.swing.JButton();
        txtDniBuscarBusqueda = new javax.swing.JTextField();
        panelDatosInicio = new javax.swing.JPanel();
        txtNombresInicio = new javax.swing.JTextField();
        txtTipoVacunaInicio = new javax.swing.JTextField();
        txtCelularInicio = new javax.swing.JTextField();
        txtCiudadInicio = new javax.swing.JTextField();
        txtCorreoInicio = new javax.swing.JTextField();
        btnRegistrarInicio = new javax.swing.JButton();
        btnNuevoInicio = new javax.swing.JButton();
        btnActualizarInicio = new javax.swing.JButton();
        panelFechaPD_Inicio = new javax.swing.JPanel();
        cbxDiaPD = new javax.swing.JComboBox<>();
        cbxAnioPD = new javax.swing.JComboBox<>();
        cbxMesPD = new javax.swing.JComboBox<>();
        PanelFechaTD_Inicio = new javax.swing.JPanel();
        cbxDiaTD = new javax.swing.JComboBox<>();
        cbxMesTD = new javax.swing.JComboBox<>();
        cbxAnioTD = new javax.swing.JComboBox<>();
        txtDniInicio = new javax.swing.JTextField();
        btnEliminarInicio = new javax.swing.JButton();
        cbxSexoInicio = new javax.swing.JComboBox<>();
        txtEdadInicio = new javax.swing.JTextField();
        PanelFechaSD_Inicio1 = new javax.swing.JPanel();
        cbxDiaSD = new javax.swing.JComboBox<>();
        cbxMesSD = new javax.swing.JComboBox<>();
        cbxAnioSD = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chbEdit = new javax.swing.JCheckBox();
        pnlTituloBD = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbBD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE CIUDADANOS VACUNADOS - COVID 19");

        panelPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        panelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPrincipalMouseClicked(evt);
            }
        });

        panelInicio.setBackground(new java.awt.Color(204, 255, 204));
        panelInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        panelInicio.setForeground(new java.awt.Color(0, 204, 204));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTituloInicio.setBackground(new java.awt.Color(51, 255, 204));
        panelTituloInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(51, 51, 255));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("COVID - 19");
        panelTituloInicio.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 610, -1));

        lblTitulo1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(51, 51, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("REGISTRO DE CIUDADANOS VACUNADOS");
        panelTituloInicio.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 660, -1));

        panelInicio.add(panelTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 776, -1));

        panelBusquedaInicio.setBackground(new java.awt.Color(204, 204, 255));
        panelBusquedaInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusquedaInicio.setForeground(new java.awt.Color(255, 255, 255));
        panelBusquedaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBusquedaInicio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBusquedaInicio.setForeground(new java.awt.Color(102, 102, 102));
        lblBusquedaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusquedaInicio.setText("Búsqueda");
        panelBusquedaInicio.add(lblBusquedaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 272, -1));

        btnBuscarBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarBusqueda.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBuscarBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/persona-soltera.png"))); // NOI18N
        btnBuscarBusqueda.setText("Buscar");
        btnBuscarBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBusquedaActionPerformed(evt);
            }
        });
        panelBusquedaInicio.add(btnBuscarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 105, 41));

        txtDniBuscarBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtDniBuscarBusqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDniBuscarBusqueda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDniBuscarBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingresar DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        panelBusquedaInicio.add(txtDniBuscarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 149, -1));

        panelInicio.add(panelBusquedaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 120));

        panelDatosInicio.setBackground(new java.awt.Color(102, 204, 255));
        panelDatosInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDatosInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombresInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtNombresInicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombresInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombresInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtNombresInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 339, -1));

        txtTipoVacunaInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoVacunaInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoVacunaInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTipoVacunaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tipo de Vacuna", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtTipoVacunaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 285, 204, 49));

        txtCelularInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtCelularInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCelularInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCelularInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Celular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtCelularInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 293, 205, -1));

        txtCiudadInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudadInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCiudadInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCiudadInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtCiudadInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 352, 205, -1));

        txtCorreoInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCorreoInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCorreoInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Correo Electrónico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtCorreoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, 382, -1));

        btnRegistrarInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarInicio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrarInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Laptop.png"))); // NOI18N
        btnRegistrarInicio.setText("Registrar");
        btnRegistrarInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarInicioActionPerformed(evt);
            }
        });
        panelDatosInicio.add(btnRegistrarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 162, 50));

        btnNuevoInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoInicio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNuevoInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Banca.png"))); // NOI18N
        btnNuevoInicio.setText("Nuevo");
        btnNuevoInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoInicioActionPerformed(evt);
            }
        });
        panelDatosInicio.add(btnNuevoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 162, 50));

        btnActualizarInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarInicio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnActualizarInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Usuario.png"))); // NOI18N
        btnActualizarInicio.setText("Actualizar");
        btnActualizarInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInicioActionPerformed(evt);
            }
        });
        panelDatosInicio.add(btnActualizarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 162, 49));

        panelFechaPD_Inicio.setBackground(new java.awt.Color(255, 255, 255));
        panelFechaPD_Inicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha - Primera Dosis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        cbxDiaPD.setBackground(new java.awt.Color(255, 255, 255));
        cbxDiaPD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxDiaPD.setForeground(new java.awt.Color(102, 102, 102));
        cbxDiaPD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Día>" }));
        cbxDiaPD.setToolTipText("");

        cbxAnioPD.setBackground(new java.awt.Color(255, 255, 255));
        cbxAnioPD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxAnioPD.setForeground(new java.awt.Color(102, 102, 102));
        cbxAnioPD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2021", "2022", "2023" }));

        cbxMesPD.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesPD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxMesPD.setForeground(new java.awt.Color(102, 102, 102));
        cbxMesPD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>" }));

        javax.swing.GroupLayout panelFechaPD_InicioLayout = new javax.swing.GroupLayout(panelFechaPD_Inicio);
        panelFechaPD_Inicio.setLayout(panelFechaPD_InicioLayout);
        panelFechaPD_InicioLayout.setHorizontalGroup(
            panelFechaPD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaPD_InicioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbxDiaPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxMesPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxAnioPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaPD_InicioLayout.setVerticalGroup(
            panelFechaPD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaPD_InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFechaPD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDiaPD)
                    .addComponent(cbxAnioPD)
                    .addComponent(cbxMesPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosInicio.add(panelFechaPD_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 280, -1));

        PanelFechaTD_Inicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelFechaTD_Inicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha - Tercera Dosis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        cbxDiaTD.setBackground(new java.awt.Color(255, 255, 255));
        cbxDiaTD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxDiaTD.setForeground(new java.awt.Color(102, 102, 102));
        cbxDiaTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Día>" }));

        cbxMesTD.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesTD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxMesTD.setForeground(new java.awt.Color(102, 102, 102));
        cbxMesTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>" }));

        cbxAnioTD.setBackground(new java.awt.Color(255, 255, 255));
        cbxAnioTD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxAnioTD.setForeground(new java.awt.Color(102, 102, 102));
        cbxAnioTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2021", "2022", "2023" }));

        javax.swing.GroupLayout PanelFechaTD_InicioLayout = new javax.swing.GroupLayout(PanelFechaTD_Inicio);
        PanelFechaTD_Inicio.setLayout(PanelFechaTD_InicioLayout);
        PanelFechaTD_InicioLayout.setHorizontalGroup(
            PanelFechaTD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFechaTD_InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxDiaTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxMesTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxAnioTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFechaTD_InicioLayout.setVerticalGroup(
            PanelFechaTD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFechaTD_InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFechaTD_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxAnioTD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cbxMesTD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDiaTD))
                .addContainerGap())
        );

        panelDatosInicio.add(PanelFechaTD_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 280, -1));

        txtDniInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtDniInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDniInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDniInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtDniInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 293, 157, -1));

        btnEliminarInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarInicio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEliminarInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/limpiar.png"))); // NOI18N
        btnEliminarInicio.setText("Eliminar");
        btnEliminarInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInicioActionPerformed(evt);
            }
        });
        panelDatosInicio.add(btnEliminarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 271, 165, 46));

        cbxSexoInicio.setBackground(new java.awt.Color(255, 255, 255));
        cbxSexoInicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbxSexoInicio.setForeground(new java.awt.Color(102, 102, 102));
        cbxSexoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Masculino", "Femenino" }));
        cbxSexoInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(cbxSexoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 210, 50));

        txtEdadInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtEdadInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        panelDatosInicio.add(txtEdadInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 119, 40));

        PanelFechaSD_Inicio1.setBackground(new java.awt.Color(255, 255, 255));
        PanelFechaSD_Inicio1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha - Segunda Dosis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        cbxDiaSD.setBackground(new java.awt.Color(255, 255, 255));
        cbxDiaSD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxDiaSD.setForeground(new java.awt.Color(102, 102, 102));
        cbxDiaSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Día>" }));

        cbxMesSD.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesSD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxMesSD.setForeground(new java.awt.Color(102, 102, 102));
        cbxMesSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>" }));

        cbxAnioSD.setBackground(new java.awt.Color(255, 255, 255));
        cbxAnioSD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxAnioSD.setForeground(new java.awt.Color(102, 102, 102));
        cbxAnioSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2021", "2022", "2023" }));

        javax.swing.GroupLayout PanelFechaSD_Inicio1Layout = new javax.swing.GroupLayout(PanelFechaSD_Inicio1);
        PanelFechaSD_Inicio1.setLayout(PanelFechaSD_Inicio1Layout);
        PanelFechaSD_Inicio1Layout.setHorizontalGroup(
            PanelFechaSD_Inicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFechaSD_Inicio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxDiaSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxMesSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxAnioSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFechaSD_Inicio1Layout.setVerticalGroup(
            PanelFechaSD_Inicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFechaSD_Inicio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFechaSD_Inicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxAnioSD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cbxMesSD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDiaSD))
                .addContainerGap())
        );

        panelDatosInicio.add(PanelFechaSD_Inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, -1));

        panelInicio.add(panelDatosInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 820, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/covid19-minsa-datosabiertos-caso4.jpg"))); // NOI18N
        panelInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WhatsApp Image 2022-04-25 at 11.02.08 AM.jpg"))); // NOI18N
        panelInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        lblInformacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInicio.add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 288, 30));

        panelPrincipal.addTab("Inicio", panelInicio);

        jPanel4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chbEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chbEdit.setText("Editar");
        chbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEditActionPerformed(evt);
            }
        });
        jPanel4.add(chbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 124, 1061, -1));

        pnlTituloBD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("COVID - 19");
        pnlTituloBD.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, 691, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("REGISTRO DE CIUDADANOS VACUNADOS");
        pnlTituloBD.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 691, -1));

        jPanel4.add(pnlTituloBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 703, -1));

        jtbBD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtbBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbBD.setColumnSelectionAllowed(true);
        jtbBD.setRowHeight(18);
        jScrollPane2.setViewportView(jtbBD);
        jtbBD.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1200, 530));

        panelPrincipal.addTab("Base de Datos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPrincipal.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEditActionPerformed
        // Condicional del editar
        if (chbEdit.isSelected()) {
            jtbBD.setEnabled(true);
        } else {
            jtbBD.setEnabled(false);
        }
    }//GEN-LAST:event_chbEditActionPerformed

    private void btnEliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInicioActionPerformed
        // Evento de eliminar para que borre un registro
        try {
            PreparedStatement pst = conect.prepareStatement("delete from vacunados where Dni = ?");

            pst.setString(1, txtDniBuscarBusqueda.getText().trim());
            pst.executeUpdate();

            // Borrar todo
            cbxDiaPD.setSelectedIndex(0);
            cbxMesPD.setSelectedIndex(0);
            cbxAnioPD.setSelectedIndex(0);
            cbxDiaSD.setSelectedIndex(0);
            cbxMesSD.setSelectedIndex(0);
            cbxAnioSD.setSelectedIndex(0);
            cbxDiaTD.setSelectedIndex(0);
            cbxMesTD.setSelectedIndex(0);
            cbxAnioTD.setSelectedIndex(0);
            txtNombresInicio.setText("");
            txtNombresInicio.requestFocus();
            txtEdadInicio.setText("");
            cbxSexoInicio.setSelectedIndex(0);
            txtTipoVacunaInicio.setText("");
            txtDniInicio.setText("");
            txtCelularInicio.setText("");
            txtCorreoInicio.setText("");
            txtCiudadInicio.setText("");
            lblInformacion.setText("Registro Eliminado");

        } catch (Exception e) {
        }
        mostrar();
    }//GEN-LAST:event_btnEliminarInicioActionPerformed

    private void btnActualizarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInicioActionPerformed
        // Evento del boton Actualizar
        String pFechaPD, pFechaSD, pFechaTD;
        pFechaPD = cbxDiaPD.getSelectedItem().toString().trim() + "/" + cbxMesPD.getSelectedItem().toString().trim() + "/" + cbxAnioPD.getSelectedItem().toString().trim();
        pFechaSD = cbxDiaSD.getSelectedItem().toString().trim() + "/" + cbxMesSD.getSelectedItem().toString().trim() + "/" + cbxAnioSD.getSelectedItem().toString().trim();
        pFechaTD = cbxDiaTD.getSelectedItem().toString().trim() + "/" + cbxMesTD.getSelectedItem().toString().trim() + "/" + cbxAnioTD.getSelectedItem().toString().trim();
        try {
            String codTemp = txtDniBuscarBusqueda.getText().trim();
            PreparedStatement pst = conect.prepareStatement("update vacunados set Fecha_PD = ?, Fecha_SD = ?, Nombre = ?, Edad = ?, Sexo=?, Codigo_Vacuna=?, Celular = ?, Correo_Electrónico = ?, Ciudad = ? where Dni = " + codTemp);
            pst.setString(1, pFechaPD);
            pst.setString(2, pFechaSD);
            pst.setString(2, pFechaTD);
            pst.setString(3, txtNombresInicio.getText().trim());
            pst.setString(4, txtEdadInicio.getText().trim());
            pst.setString(5, cbxSexoInicio.getSelectedItem().toString());
            pst.setString(6, txtTipoVacunaInicio.getText().trim());
            pst.setString(7, txtCelularInicio.getText().trim());
            pst.setString(8, txtCorreoInicio.getText().trim());
            pst.setString(9, txtCiudadInicio.getText().trim());
            pst.executeUpdate();
            lblInformacion.setText("Actualización de Datos Exitosa.");
        } catch (Exception e) {
            lblInformacion.setText("ERROR: " + e);
        }
        mostrar();
    }//GEN-LAST:event_btnActualizarInicioActionPerformed

    private void btnNuevoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoInicioActionPerformed
        // Borrar todo
        cbxDiaPD.setSelectedIndex(0);
        cbxMesPD.setSelectedIndex(0);
        cbxAnioPD.setSelectedIndex(0);
        cbxDiaSD.setSelectedIndex(0);
        cbxMesSD.setSelectedIndex(0);
        cbxAnioSD.setSelectedIndex(0);
        cbxDiaTD.setSelectedIndex(0);
        cbxMesTD.setSelectedIndex(0);
        cbxAnioTD.setSelectedIndex(0);
        txtNombresInicio.setText("");
        txtNombresInicio.requestFocus();
        txtEdadInicio.setText("");
        cbxSexoInicio.setSelectedIndex(0);
        txtTipoVacunaInicio.setText("");
        txtDniInicio.setText("");
        txtCelularInicio.setText("");
        txtCorreoInicio.setText("");
        txtCiudadInicio.setText("");
        lblInformacion.setText("");

    }//GEN-LAST:event_btnNuevoInicioActionPerformed

    private void btnRegistrarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarInicioActionPerformed
        // Evento del Boton registrar
        String pFechaPD, pFechaSD, pFechaTD, pNombre, pSexo, pCodigoVacuna, pCorreo, pCiudad;
        int pEdad, pDni, pCelular;
        DefaultTableModel TablaVacunados = new DefaultTableModel();
        //Obtener los datos que entran por teclado
        pFechaPD = cbxDiaPD.getSelectedItem().toString().trim() + "/" + cbxMesPD.getSelectedItem().toString().trim() + "/" + cbxAnioPD.getSelectedItem().toString().trim();
        pFechaSD = cbxDiaSD.getSelectedItem().toString().trim() + "/" + cbxMesSD.getSelectedItem().toString().trim() + "/" + cbxAnioSD.getSelectedItem().toString().trim();
        pFechaTD = cbxDiaTD.getSelectedItem().toString().trim() + "/" + cbxMesTD.getSelectedItem().toString().trim() + "/" + cbxAnioTD.getSelectedItem().toString().trim();
        pNombre = txtNombresInicio.getText();
        pEdad = Integer.parseInt(txtEdadInicio.getText().trim());
        pSexo = cbxSexoInicio.getSelectedItem().toString();
        pCodigoVacuna = txtTipoVacunaInicio.getText().trim();
        pDni = Integer.parseInt(txtDniInicio.getText().trim());
        pCelular = Integer.parseInt(txtCelularInicio.getText().trim());
        pCorreo = txtCorreoInicio.getText().trim();
        pCiudad = txtCiudadInicio.getText();
        ClaseLlenado llenado = new ClaseLlenado(pFechaPD, pFechaSD, pFechaTD, pNombre, pEdad, pSexo, pCodigoVacuna, pDni, pCelular, pCorreo, pCiudad);
        lista.add(llenado);
        // Conección a una base de datos
        // Connection conexion= DriverManager.getConection(-Ruta y el nombre de la BD a conectar -," Nombre de la BD","Contraseña de la BD");
        try {
            PreparedStatement pst = conect.prepareStatement("insert into vacunados values(?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, pFechaPD);
            pst.setString(2, pFechaSD);
            pst.setString(3, pFechaTD);
            pst.setString(4, pNombre);
            pst.setString(5, String.valueOf(pEdad));
            pst.setString(6, pSexo);
            pst.setString(7, pCodigoVacuna);
            pst.setString(8, String.valueOf(pDni));
            pst.setString(9, String.valueOf(pCelular));
            pst.setString(10, pCorreo);
            pst.setString(11, pCiudad);
            pst.executeUpdate();
            // Borrar todo
            cbxDiaPD.setSelectedIndex(0);
            cbxMesPD.setSelectedIndex(0);
            cbxAnioPD.setSelectedIndex(0);
            cbxDiaSD.setSelectedIndex(0);
            cbxMesSD.setSelectedIndex(0);
            cbxAnioSD.setSelectedIndex(0);
            cbxDiaTD.setSelectedIndex(0);
            cbxMesTD.setSelectedIndex(0);
            cbxAnioTD.setSelectedIndex(0);
            txtNombresInicio.setText("");
            txtNombresInicio.requestFocus();
            txtEdadInicio.setText("");
            cbxSexoInicio.setSelectedIndex(0);
            txtTipoVacunaInicio.setText("");
            txtDniInicio.setText("");
            txtCelularInicio.setText("");
            txtCorreoInicio.setText("");
            txtCiudadInicio.setText("");
            lblInformacion.setText("El ciudadano fue registrado");
        } catch (Exception ex) {
            lblInformacion.setText("No es posible conectar con la base de datos.");
        }
        mostrar();
    }//GEN-LAST:event_btnRegistrarInicioActionPerformed

    private void btnBuscarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBusquedaActionPerformed
        // Declaración de Variables para separar la fecha
        String fechaPD, fechaSD, fechaTD, diaPD, diaSD, diaTD, mesPD, mesSD, mesTD, anioSD, aniosPD,aniosTD;
        // Evento de búsqueda en la base de datos.
        try {
            PreparedStatement pst = conect.prepareStatement("select * from vacunados where Dni = ?");
            // enviar a la base de datos el valor a buscar
            pst.setString(1, txtDniBuscarBusqueda.getText().trim());
            // clase que permite saber si encontró el valor
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                fechaPD = rs.getString("Fecha_PD");
                fechaSD = rs.getString("Fecha_SD");
                fechaTD = rs.getString("Fecha_TD");

                diaPD = fechaPD.split("/")[0];
                mesPD = fechaPD.split("/")[1];
                aniosPD = fechaPD.split("/")[2];
                diaSD = fechaSD.split("/")[0];
                mesSD = fechaSD.split("/")[1];
                anioSD = fechaSD.split("/")[2];
                diaTD = fechaTD.split("/")[0];
                mesTD = fechaTD.split("/")[1];
                aniosTD = fechaTD.split("/")[2];
                cbxDiaPD.setSelectedItem(diaPD);
                cbxDiaSD.setSelectedItem(diaSD);
                cbxDiaTD.setSelectedItem(diaTD);
                cbxMesPD.setSelectedItem(mesPD);
                cbxMesSD.setSelectedItem(mesSD);
                cbxMesTD.setSelectedItem(mesTD);
                cbxAnioPD.setSelectedItem(aniosPD);
                cbxAnioSD.setSelectedItem(anioSD);
                cbxAnioTD.setSelectedItem(aniosTD);
                txtNombresInicio.setText(rs.getString("Nombre"));
                txtEdadInicio.setText(rs.getString("Edad"));
                cbxSexoInicio.setSelectedItem(rs.getString("Sexo"));
                txtTipoVacunaInicio.setText(rs.getString("Codigo_Vacuna"));
                txtDniInicio.setText(rs.getString("Dni"));
                txtCelularInicio.setText(rs.getString("Celular"));
                txtCorreoInicio.setText(rs.getString("Correo_Electrónico"));
                txtCiudadInicio.setText(rs.getString("Ciudad"));
                lblInformacion.setText("Consulta Exitosa");
            } else {
                lblInformacion.setText("Participante no encontrado");
            }
        } catch (Exception e) {
            lblInformacion.setText("Error: " + e);
        }
    }//GEN-LAST:event_btnBuscarBusquedaActionPerformed

    private void panelPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrincipalMouseClicked
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_panelPrincipalMouseClicked
    @SuppressWarnings("empty-statement")
    public void mostrar() {
        DefaultTableModel TablaVacunados = new DefaultTableModel();
        TablaVacunados.addColumn("Fecha - Primera Dosis");
        TablaVacunados.addColumn("Fecha - Segunda Dosis");
        TablaVacunados.addColumn("Fecha - Tercera Dosis");
        TablaVacunados.addColumn("Nombre");
        TablaVacunados.addColumn("Edad");
        TablaVacunados.addColumn("Sexo");
        TablaVacunados.addColumn("Tipo de Vacuna");
        TablaVacunados.addColumn("Dni");
        TablaVacunados.addColumn("Celular");
        TablaVacunados.addColumn("Correo Electrónico");
        TablaVacunados.addColumn("Ciudad");
        jtbBD.setModel(TablaVacunados);
        try {
            Statement leer = conect.createStatement();
            ResultSet rs = leer.executeQuery("select * from vacunados");
            String matriz[] = new String[11];
            while (rs.next()) {
                matriz[0] = rs.getString("Fecha_PD");
                matriz[1] = rs.getString("Fecha_SD");
                matriz[2] = rs.getString("Fecha_TD");
                matriz[3] = rs.getString("Nombre");
                matriz[4] = rs.getString("Edad");
                matriz[5] = rs.getString("Sexo");
                matriz[6] = rs.getString("Codigo_Vacuna");
                matriz[7] = rs.getString("Dni");
                matriz[8] = rs.getString("Celular");
                matriz[9] = rs.getString("Correo_Electrónico");
                matriz[10] = rs.getString("Ciudad");
                TablaVacunados.addRow(matriz);
            }
            jtbBD.setModel(TablaVacunados);
        } catch (Exception e) {
            lblInformacion.setText("Error papi");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFechaSD_Inicio1;
    private javax.swing.JPanel PanelFechaTD_Inicio;
    private javax.swing.JButton btnActualizarInicio;
    private javax.swing.JButton btnBuscarBusqueda;
    private javax.swing.JButton btnEliminarInicio;
    private javax.swing.JButton btnNuevoInicio;
    private javax.swing.JButton btnRegistrarInicio;
    private javax.swing.JComboBox<String> cbxAnioPD;
    private javax.swing.JComboBox<String> cbxAnioSD;
    private javax.swing.JComboBox<String> cbxAnioTD;
    private javax.swing.JComboBox<String> cbxDiaPD;
    private javax.swing.JComboBox<String> cbxDiaSD;
    private javax.swing.JComboBox<String> cbxDiaTD;
    private javax.swing.JComboBox<String> cbxMesPD;
    private javax.swing.JComboBox<String> cbxMesSD;
    private javax.swing.JComboBox<String> cbxMesTD;
    private javax.swing.JComboBox<String> cbxSexoInicio;
    private javax.swing.JCheckBox chbEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbBD;
    private javax.swing.JLabel lblBusquedaInicio;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel panelBusquedaInicio;
    private javax.swing.JPanel panelDatosInicio;
    private javax.swing.JPanel panelFechaPD_Inicio;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JPanel panelTituloInicio;
    private javax.swing.JPanel pnlTituloBD;
    private javax.swing.JTextField txtCelularInicio;
    private javax.swing.JTextField txtCiudadInicio;
    private javax.swing.JTextField txtCorreoInicio;
    private javax.swing.JTextField txtDniBuscarBusqueda;
    private javax.swing.JTextField txtDniInicio;
    private javax.swing.JTextField txtEdadInicio;
    private javax.swing.JTextField txtNombresInicio;
    private javax.swing.JTextField txtTipoVacunaInicio;
    // End of variables declaration//GEN-END:variables
}
